# Generated by Django 5.2.6 on 2025-12-27 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ACTIVE', 'Active'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')])),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('detection_count', models.IntegerField(default=0)),
                ('max_confidence', models.FloatField(default=0)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')])),
                ('message', models.TextField(max_length=100)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('BOTH', 'Both')])),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')])),
                ('has_detections', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('image_format', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('storage_path', models.CharField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')])),
                ('has_detections', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField()),
                ('video', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('duration', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('frame_rate', models.FloatField()),
                ('codec', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_obj', models.CharField(choices=[('PERSON', 'Person'), ('ANIMAL', 'Aninal'), ('VEHICLE', 'Vehicle'), ('UNKNOWN_OBJECT', 'Unknown Object'), ('False', 'Multiple Objects')])),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(default=0)),
                ('label', models.CharField()),
                ('model_version', models.CharField()),
                ('bounding_box', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
